name: react_bootstrap
description: A Dart wrapper for the JavaScript react-bootstrap library.
version: 0.0.1
author: <Jonas Kello> <jonas.kello@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.9.0 <2.0.0'
